server:
  port : 8081

spring:
    datasource:
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:totoList
      username: Yancy
      password: 123
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
    h2:
      console.enabled: true